### ISSUE TITLE
Wasm 32-bit support (Windows i686, Linux armhf)

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#757]
This is a parent thread to follow outside work on 32-bit Wasm.

As WebAssembly is the candidate of choice to replace NaCl, it is interesting to look at what platform it supports. Tracking this is low priority but it's not a bad idea to gather the related knowledge and have a place to track this in a dedicated place.

The NaCl stack we use provides ability to build and run 64-bit amd64 and 32-bit i686, armhf and mips binaries (I doubt there is a single compatible mips platform though). There may be a 64-bit arm65 support in NaCl repository, but a build for it haven't been found yet.

The Wasmtime runtime provides support for 64-bit amd64, arm64, riscv64 and s390x (I doubt we would have a single s390x user though). There is no supported 32-bit platform at all.

Among existing 32-bit platform around, the major interests are in:

- Windows i686, Windows users who got a 32-bit Windows typically don't replace it with a 64-bit Windows. A lot of computers pre-installed with 32-bit Windows were sold very lately, even if running on 64-bit compatible hardware.
- Linux armhf, usage of 32-bit armhf Linux distributions is very common arm64 boards. For example the default and recommended operating system download for the well-known raspberry pi is 32-bit, even if the CPU is compatible 64-bit and there are 64-bit operating system alternate download available. Some proprietary drivers for some GPUs commonly found on arm64 boards may even be 32-bit only.

As @necessarily-equal wrote in https://github.com/Unvanquished/Unvanquished/issues/1015

> https://docs.wasmtime.dev/stability-platform-support.html#jit-compiler-support they seem to say 32 bits support is "planned". The compilation error that you have seen was apparently introduced by https://github.com/bytecodealliance/wasmtime/pull/5226 or a similar PR. It seems the hard part of doing this isn't in wasmtime, but in cranelift.
>
> Adding 32 bits support would be tracked in https://github.com/bytecodealliance/wasmtime/issues/1980 for wasmtime, but no one seems to be working on it at the moment. I honestly doubt someone will feel motivated enough to add support for that, so I'd rather plan the "no 32 bit support" case than the other way around.

**Comment by illwieckz** [comment]
About Wasm and 32-bit, I read a [very interesting comment](https://github.com/WebAssembly/design/issues/1397#issuecomment-963561649) on WebAssembly design tracker (comment from 2021):

> It is definitely true that almost all new sold Android devices are 64-bit (although last time I looked in 2020, there were surprisingly still new 32-bit Android devices coming out in India and Pakistan markets), and we do also see this in our analytics. For the overall marketshare, in our analytics we do not reach a 90% prevalence count, and actually not even a 80% bar.
>
> However the actual issue is that Chrome on Android has not yet completed its 64-bit transition. According to [this source](https://www.androidpolice.com/2021/03/15/these-android-devices-are-eligible-for-64-bit-chrome/), the requirements for getting an automatic update to 64-bit Chrome is to have Android 10 with at least 8GB of RAM on the device. […]
>
> The average gaming phones that are sold to the market in 2021 have just 4GB of RAM. […] Based on the above Chromium blog post paired with our analytics, I do not expect 64-bit Chrome overtaking 90% adoption rate within the next three years at least with the current trajectory.

So, while we don't run Android, it gives us a glance on what kind of hardware platforms Wasm is expected to run. The same way there was actually 32-bit versions Windows 10 being distributed (even if hardware can do 64-bit), there are 32-bit Android being distributed, or even 32-bit Chrome (even if hardware can do 64-bit), sometime just to save on memory.

So the same way we need to ship i686 build of our game for 32-bit Windows 10, some others may have to port Wasm to 32-bit arm for running web apps on phones.

**Comment by necessarily-equal** [comment]
While this is interesting, it kind of suggest the only reason 32 bits wasm is available is to save memory, or cheap android phone. We don't want to support cheap android phones; and running 32 bits wasm executable is actually the wasmtime default anyway https://github.com/bytecodealliance/wasmtime/issues/572, https://github.com/bytecodealliance/wasmtime/pull/3153.

"Runs 32 bits executables" and "Runs on a 32 bits CPU" are very different problems. And for our usecase we don't need to care about 64 bits devices equipped only with 32 bits runtimes because we *own* the runtime.

**Comment by illwieckz** [comment]
> "Runs 32 bits executables" and "Runs on a 32 bits CPU" are very different problems. And for our usecase we don't need to care about 64 bits devices equipped only with 32 bits runtimes because we own the runtime.

I don't get this. There is no wasmtime runtime to build or download to redistribute, so we cannot distribute a 32-bit wasmtime runtime on Windows i686 (Like on 32-bit Windows-10) or Linux armhf (like on Raspberry Pi default distro).

**Comment by illwieckz** [comment]
[WAMR](https://github.com/bytecodealliance/wasm-micro-runtime) (WASM micro runtime) may be a better candidate than wasmtime: it supports all platforms the engine currently run on, it has more hardware compatibility than both NaCl and Wasmtime.

I updated the table in first post.

**Comment by illwieckz** [comment]
I built the toolchain and the virtual machine of WAMR, and I modified their benchmark script to also run `coremark` on NaCl, here is the results, comparing native (x86_64) to NaCl (x86_64) to Wasm (WAMR):

platform|ticks|time|iterations/s|performance losss compared to native
--|--|--|--|--
native|13379|13.379000|29897.600718|0%
nacl_loader|19327|19.327000|20696.435039|-30.78%
iwasm aot|16776|16.776000|23843.586075|-20.25%
iwasm aot-segue|14890|14.890000|26863.666891|-10.15%
iwasm interpreter|214804|214.804000|1862.162716|-93.77%

More iterations per second means the executable runs faster.

Details provided by `coremark` when running (common to all runs):

```
2K performance run parameters for coremark.
Iterations       : 400000
```

When running `coremark`, WAMR is faster than NaCL.

**Comment by illwieckz** [comment]
For information, q3now implemented Wasm as a replacement for QVM using WAMR:

There are interesting things to read there:

- https://github.com/eser/q3now/blob/main/WASM.md

**Comment by illwieckz** [comment]
I updated the table in the first post with current knowledge.

**Comment by illwieckz** [comment]
Once thing to know is that wasmtime implemented an interpreter, meaning it can work on every platform that is not specifically implemented, but that may be very slow.

**Comment by illwieckz** [comment]
Maybe it would be possible to build a single Wasm binary but ship the engine with either Wasmtime or WAMR according to the platform, either because one of them has hardware support, either because none implement hardware support and we need the interpreter.
